services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    command: go run main.go -b 0.0.0.0
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
