services:
- type: web
  name: web 
  runtime: go
  dockerfilePath: ./Dockerfile.web
  envVars:
    - key: PORT
      value: 8000

- type: web
  name: nginx
  runtime: docker
  dockerfilePath: ./Dockerfile.nginx
  envVars: 
    - key: PORT
      value: 8080
